

#设置提供的服务名
spring:
  application:
    name: @artifactId@

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  #json字符串格式化
  jackson:
    serialization:
      indent-output: true

  #  当Spring Boot 2.6.x 和Swagger 3.0.0 整合的时候，可能会报错如下所示：除了SwaggerConfiguration有改动外，这里需要加上
  #  原因： 这是因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://dbserver:3306/ticket?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useAffectedRows=true
    username: root
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 500
      max-wait: 5000
      min-idle: 2
      initial-size: 2

  # Redis配置
  redis:
    database: 0
    host: m.jutrade.cn
    password: redispassword
    port: 6379
    timeout: 50000
    jedis:
      pool:
        max-idle: 200
        min-idle: 200
        max-active: 2000
        max-wait: 1000

#打印SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #指明mapper.xml扫描位置(classpath* 代表编译后类文件根目录)
    mapper-locations: classpath*:/mapper/**Mapper.xml
    #指明实体扫描(多个package用逗号或者分号分隔)
    typeAliasesPackage: cn.zhanx.project05.domain
    global-config:
      #主键类型 0:数据库ID自增, 1:用户输入ID,2:全局唯一ID (数字类型唯一ID), 3:全局唯一ID UUID
      id-type: 0
      #字段策略(拼接sql时用于判断属性值是否拼接) 0:忽略判断,1:非NULL判断,2:非空判断
      field-strategy: 2
      #驼峰下划线转换含查询column及返回column(column下划线命名create_time，返回java实体是驼峰命名createTime，开启后自动转换否则保留原样)
      db-column-underline: true
      #是否动态刷新mapper
      refresh-mapper: false
      #数据库大写命名下划线转换
      #capital-mode: true

logging:
  config: classpath:logback-spring.xml
  file:
    path: /Users/fang/logs
    #path: /home/jinlong/logs

## Feign 配置
feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 120000

feignapi:
  jutrade:
    domain: https://m.jutrade.cn

server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

